[package]
name = "domain"
version = "0.0.1"
edition = "2021"

[lib]
doctest = false

[dependencies]
num-bigint = "0.4"
chrono = "0.4"
# feature mockall
mockall = { version = "0.13", optional = true }
