[package]
name = "domain"
version = "0.0.1"
edition = "2021"

[lib]
doctest = false

[dependencies]
num-bigint = { workspace = true }
chrono = { workspace = true }
# feature mockall
mockall = { workspace = true, optional = true }
